# Generated by Django 3.2.8 on 2021-12-01 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=300, null=True)),
                ('reset_password_auth_number', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('profile_image_url', models.URLField(max_length=2000, null=True)),
                ('login_method', models.CharField(max_length=30, null=True)),
                ('platform_id', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(null=True)),
                ('user_histories', models.ManyToManyField(related_name='users_histories', through='rooms.UserRoomHistory', to='rooms.Room')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foolow_by_followed', to='users.user')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_by_users', to='users.user')),
            ],
            options={
                'db_table': 'follows',
            },
        ),
    ]
