# Generated by Django 3.2.8 on 2021-12-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_password_auth_number',
        ),
    ]
