# Generated by Django 3.2.8 on 2021-12-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_reset_password_auth_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
