# Generated by Django 3.2.8 on 2021-12-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211210_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='day_of_birth',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
