# Generated by Django 3.2.8 on 2021-12-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211210_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='platform_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
