# Generated by Django 3.2.8 on 2022-01-25 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211231_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.localtime, help_text='팔로우 추가한 시간'),
        ),
    ]
