# Generated by Django 3.2.8 on 2021-12-01 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('contents', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroomhistory',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='roomcontent',
            name='contents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.content'),
        ),
        migrations.AddField(
            model_name='roomcontent',
            name='rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomcategory'),
        ),
        migrations.AddField(
            model_name='room',
            name='rooms_contents',
            field=models.ManyToManyField(related_name='rooms', through='rooms.RoomContent', to='contents.Content'),
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='users.user'),
        ),
    ]
