# Generated by Django 3.2.8 on 2022-01-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='running_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
