# Generated by Django 3.2.8 on 2022-01-17 17:46

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='접속한 사람수', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(db_index=True, default=rooms.models._generate_room_random_id, max_length=55, primary_key=True, serialize=False),
        ),
    ]
