# Generated by Django 3.2.8 on 2022-01-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20220111_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='maximum_limit',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
