# Generated by Django 3.2.8 on 2022-01-17 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211231_1045'),
        ('rooms', '0003_auto_20220118_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='users.user'),
        ),
    ]
