# Generated by Django 3.2.8 on 2022-01-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_maximum_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='running_time',
        ),
    ]
