# Generated by Django 3.2.8 on 2022-01-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20211208_1554'),
        ('rooms', '0004_alter_room_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomcategory'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rooms_contents',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', through='rooms.RoomContent', to='contents.Content'),
        ),
    ]
