# Generated by Django 3.2.8 on 2022-01-09 14:06

import chats.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.CharField(db_index=True, default=chats.models._generate_room_random_id, max_length=55, primary_key=True, serialize=False)),
                ('user_type', models.IntegerField(choices=[(0, 'Group Chat'), (1, 'Direct Message')], default=0, help_text='채팅방 유형', verbose_name='채팅방 유형')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='메세지 작성한 시간', verbose_name='작성한 시간')),
            ],
            options={
                'verbose_name': '채팅방',
                'verbose_name_plural': '채팅방 모음',
                'db_table': 'chat_room',
                'ordering': ('created_at',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('chat_room', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='메세지 작성한 시간', verbose_name='작성한 시간')),
            ],
            options={
                'verbose_name': '채팅 메세지',
                'verbose_name_plural': '채팅 메세지 모음',
                'db_table': 'message',
                'ordering': ('created_at',),
                'managed': True,
            },
        ),
    ]
