# Generated by Django 3.2.8 on 2022-01-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_room',
            new_name='room',
        ),
    ]
